spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_chaguan

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          chaguanApply:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguan:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguanMember:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguanYushiRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberChaguanYushiRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguanShopOrder:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguanShopProduct:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chaguanDataReport:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          ruianGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          fangpaoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wenzhouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          dianpaoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wenzhouShuangkouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chayuanShuangkouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          doudizhuGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          daboluoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          paodekuaiGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameTable:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        chaguanApply:
          destination: chaguanApply
          contentType: application/json
          producer:
            partitionCount: 1
        chaguan:
          destination: chaguan
          contentType: application/json
          producer:
            partitionCount: 1
        chaguanMember:
          destination: chaguanMember
          contentType: application/json
          producer:
            partitionCount: 1
        chaguanYushiRecord:
          destination: chaguanYushiRecord
          contentType: application/json
          producer:
            partitionCount: 1
        memberChaguanYushiRecord:
          destination: memberChaguanYushiRecord
          contentType: application/json
          producer:
            partitionCount: 1
        chaguanShopOrder:
          destination: chaguanShopOrder
          contentType: application/json
          producer:
            partitionCount: 1
        chaguanShopProduct:
          destination: chaguanShopProduct
          contentType: application/json
          producer:
            partitionCount: 1
        agentAuthorization:
          destination: agentAuthorization
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        members:
          destination: members
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agents:
          destination: agents
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameServer:
          destination: gameServer
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginLimitRecord:
          destination: memberLoginLimitRecord
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameTable:
          destination: gameTable
          contentType: application/json
          producer:
            partitionCount: 1
        ruianGameRoom:
          destination: ruianGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        fangpaoGameRoom:
          destination: fangpaoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        wenzhouGameRoom:
          destination: wenzhouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        dianpaoGameRoom:
          destination: dianpaoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        wenzhouShuangkouGameRoom:
          destination: wenzhouShuangkouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        chayuanShuangkouGameRoom:
          destination: chayuanShuangkouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        doudizhuGameRoom:
          destination: doudizhuGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        daboluoGameRoom:
          destination: daboluoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        paodekuaiGameRoom:
          destination: paodekuaiGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        chayuanShuangkouGame:
          destination: chayuanShuangkouGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        chayuanShuangkouResult:
          destination: chayuanShuangkouResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        daboluoGame:
          destination: daboluoGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        daboluoResult:
          destination: daboluoResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        dianpaoMajiangGame:
          destination: dianpaoMajiangGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        dianpaoMajiangResult:
          destination: dianpaoMajiangResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        doudizhuGame:
          destination: doudizhuGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        doudizhuResult:
          destination: doudizhuResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangGame:
          destination: fangpaoMajiangGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        paodekuaiGame:
          destination: paodekuaiGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        paodekuaiResult:
          destination: paodekuaiResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        ruianMajiangGame:
          destination: ruianMajiangGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        ruianMajiangResult:
          destination: ruianMajiangResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangGame:
          destination: wenzhouMajiangGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangResult:
          destination: wenzhouMajiangResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouShuangkouGame:
          destination: wenzhouShuangkouGame
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouShuangkouResult:
          destination: wenzhouShuangkouResult
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginRecord:
          destination: memberLoginRecord
          group: qipai-chaguan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        chaguanDataReport:
          destination: chaguanDataReport
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-chaguan
server:
  port: 91
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

filepath:
  snapshotFileBasePath: /data/app/qipai_chaguan/snapshot
  jFileBasePath: /data/app/qipai_chaguan/journal